# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
  PHP: true
exclude_paths:
- "ext/*"
- "src/ext/*"
- "node_modules/*"
- "doc/scripts/*"
